# docker-compose.yml
# File: /docker-compose.yml
# Description: Docker Compose configuration for development environment
# Project: Household Chore Gamification System
# Last Modified: 2025-02-10

version: "3.8"

services:
  app:
    build:
      context: .
      target: deps
    command: npm run dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/chore_gamification
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-development-secret-key
    depends_on:
      - db

  db:
    image: postgres:15-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chore_gamification
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
