# File: /.github/workflows/ci.yml
# Description: Basic CI pipeline for running tests
# Project: Household Chore Gamification System
# Last Modified: 2025-02-11

name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "23"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run type-check
        run: npm run type-check

      - name: Run lint
        run: npm run lint
